#!/usr/bin/env php
<?php

use Hp\Phpexe\Commands\MainCommands;

require_once(__DIR__ . '/vendor/autoload.php');
require_once(__DIR__ . '/tools.php');
require_once(__DIR__ . '/config.php');



$commands = new MainCommands();

$commands->handler($argv);
